### ISSUE TITLE
[enhancement]Add sidebar when entering via tag

### ISSUE THREAD

**Issue by colommar** [maodaisuki/blog#17]
Hello, sometimes when browsing my blog via tags, I find this can be difficult, I would like to ask if it is possible to add a sidebar to make my browsing easier?

**Comment by maodaisuki** [comment]
你好，可以给一个示意草图吗？

**Comment by colommar** [comment]
当然，这是我的设想，有了这个tag索引会能让我记录的内容翻阅起来更加方便。
![49614b8be259657c10f334d876aead5](https://github.com/maodaisuki/blog/assets/117348480/5614ccb1-a579-4999-adbb-1707ca0261d2)
![317c8b2704bccd4438aa2d6f90362fa](https://github.com/maodaisuki/blog/assets/117348480/7abf67e6-3867-4ee9-943f-cae476ba8111)
![5ce9f632bf216da450bc811d4e82a9e](https://github.com/maodaisuki/blog/assets/117348480/ca775804-aa05-494d-a70c-5a482c44e6cc)

**Comment by maodaisuki** [comment]
暂时不会考虑添加侧边栏，但之后可能会重写 Tags 页面，添加标签过滤功能。 #18
